<?php

/*
var $id = NULL;
var $titel = NULL;
var $url = NULL;
var $autor_id = NULL;
var $datum = NULL;
var $werk_id = NULL;
var $verlag_id = NULL;
var $notenschrift_cd integer = NULL;
var $vers_nr = NULL;
var $rhythmus_gerade = NULL;
var $rhythmus_ungerade = NULL;
var $rhythmus_gemischt = NULL;
var $rhythmus_bemerkungen = NULL;
var $bemerkungen = NULL;
var $copyright_datum = NULL;
var $rec_created = NULL;
var $rec_last_updated = NULL;
*/

$testdata = array (
//  'id' => NULL,
     'titel' => 'TEST: Titel'
    ,'url' => 'rabarber.pdf'
    ,'autor_id' => 1
    ,'datum' => date("Y-m-d")                   
    ,'werk_id' => NULL
    ,'verlag_id' => NULL
//    ,'notenschrift_cd integer' => NULL
    ,'vers_nr' => NULL
    ,'rhythmus_gerade' => 'TRUE'
    ,'rhythmus_ungerade' => 'FALSE'
    ,'rhythmus_gemischt' => 'FALSE'
    ,'rhythmus_bemerkungen' => 'TEST: Rhythmus-Bemerkungen'
    ,'bemerkungen' => 'TEST: Bemerkungen... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber... Rabarber'
    ,'copyright_datum' => date("Y-m-d")
//  ,'rec_created' => NULL
//  ,'rec_last_updated' => NULL
);

?>
